# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RiGn5iTC_yWeBeH_ZXxbcoY_FO6xsY9K
"""

import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf

# dataset
dataset = pd.read_csv('cancer.csv')

# target variables
x = dataset.drop(columns=["diagnosis(1=m, 0=b)"])
y = dataset["diagnosis(1=m, 0=b)"]

# training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# the model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(256, input_shape=(x_train.shape[1],), activation='sigmoid'))
model.add(tf.keras.layers.Dense(256, activation='sigmoid'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# Compiling model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=1000)

model.evaluate(x_test, y_test)

